下記の通り、仕様変更と機能追加を行った。
corakt/MiniatureGardenTanks pull request #2
Opened 2019-04-23 05:50 UTC by takuya1026

・プログラム全体のベースとなるクラス「Object」を「GameObject」に名前を変更した。

・プログラムの全体のオブジェクトの種類を判別する列挙体「ObjectType」を追加した。
　それに伴い、クラス「ModelObject」からモデルの種類を表す列挙体「ModelType」を削除した。

・IDを生成するクラス「ObjectIdManager」を「IdGenerator」に名前を変更した。
　プログラム内でIDを生成する場合は、このクラスを利用する。

・クラス「GameObject」にAddComponent関数を追加した。
　この関数を利用して、コライダーやレイキャストなどの機能を新たに追加できるように仕様を変更した。
それに伴い、ショットを発射する処理が機能しなくなったため、一度コメントアウトしておく。

　現在はモデルの生成に利用する「ModelObject」のみ対応済み。

2019-04-27 05:40 UTC, vm-t-yui requested changes

2019-04-27 05:40 UTC, vm-t-yui commented on MiniatureGardenTanks/Data/SourceFiles/BaseObject/IdGenerator.h
> +
乱数発生器はわかりやすいメンバ名をつけてほしい

2019-04-27 05:40 UTC, vm-t-yui commented on MiniatureGardenTanks/Data/SourceFiles/Character/CharacterBase.cpp
呼ばれるたびに作成するなら、クラスのstaticメンバ変数にしたほうが良い
（VGetがランタイムに生成するやつでstatic constで初期化して落ちるなら最初の一回だけ初期化する形にコンストラクタで調整するとか）

2019-04-27 05:40 UTC, vm-t-yui commented on MiniatureGardenTanks/Data/SourceFiles/Character/CharacterBase.cpp
>  				onCollisionShot(collModelInfoElem);
関数の先頭が小文字なのはよくない
そもそもcommonUpdateなど「common」と名の付くものがメンバ関数としてあるのはおかしい
「クラス専門の」処理にもかかわらず「common」とは？

2019-04-27 05:40 UTC, vm-t-yui commented on MiniatureGardenTanks/Data/SourceFiles/Character/CharacterBase.cpp
>  				onCollisionShot(collModelInfoElem);
そもそも関数が長い！！

2019-05-01 05:15 UTC, vm-t-yui requested changes
static const系はメンバ変数にしましょう
ベクタ系はVGet使うと初期化をランタイム時に行わなきゃ行けない欠点があった気がしますがほかは行けるはずです

2019-05-01 05:17 UTC, vm-t-yui approved these changes
@hetaresuraimu1709 
ちょっと変更が多くなりすぎたので一旦マージします
コメントはよく見ておいてください

2019-05-01 05:17 UTC, vm-t-yui commented on MiniatureGardenTanks/Data/SourceFiles/BaseObject/ModelObject.h
> +	{
ヘッダに直接関数を書くにしては長い

2019-05-01 05:17 UTC, merged

2019-05-01 06:12 UTC, takuya1026 commented
分かりました。
ありがとうございます。